routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/exportarExcel', 'HomeController@export');
Route::get('/exportarPDF', 'HomeController@exportarPDF');

Route::resource('/cuentas','PlanCuentasController');

Route::resource('/proveedores','ProovedoresController');
Route::resource('/ordenes-de-pago','OrdenPagoController');
Route::get('/exportar-orden-pago/{id}', 'OrdenPagoController@exportarOrdenPago');

Route::get('/ver-op',function(){
    return view('reportes.orden_pago');
   // $letras = NumeroALetras::convertir(12345);
    //echo $letras;
});

Route::get('/exportar-orden-pago/{id}','OrdenPagoController@exportarOrdenPago');

Route::get('/exportarExcel', 'ProovedoresController@export');
Route::get('/exportarPDF', 'ProovedoresController@exportarPDF');

Route::get('/eliminarcuenta/{id}', 'PlanCuentasController@eliminarCuenta');
Route::post('/actualizarcuenta/', 'PlanCuentasController@actualizarCuenta')->name('actualizarcuenta');

//Route::get('/orden-de-pago','OrdenPagoController@index');

//Creditos de ejercicios 

Route::resource('/creditos-del-ejercicio','CreditoEjercicioController');
Route::get('/creditos-del-ejercicio.presupuesto','CreditoEjercicioController@presupuesto')->name('creditos-del-ejercicio.presupuesto');
Route::get('/creditos-del-ejercicio.compensacion','CreditoEjercicioController@compensacion')->name('creditos-del-ejercicio.compensacion');

Route::get('/pagos/pagar-orden-pago/{id}' , 'PagosController@payOrder')->name('pagos.create');

Route::post('/pagos/guardar-pago' , 'PagosController@savePayment')->name('pagos.guardar');

Route::get('/pagos','PagosController@index')->name('pagos.index');
Route::post('/pagos/disponibilidad-cheque' , 'PagosController@verificarDisponibilidadCheque');

app/Proveedores.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Proveedores extends Model
{
    //
}

resources/views/proveedores/create.blade.php
@extends('layouts.backend')

@section('content')
<div class="wrapper">
    <div class="row">
        <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Nuevo proveedor</h5>
            </div>
            <div class="ibox-content">
                <div class="row wrapper">
                    
                    
                    
                    <form action="{{ route('proveedores.store' ) }}" method="POST">
                        {{ csrf_field() }}
                        @include('proveedores.fragment.form')
                    </form>
                </div>
            </div>
        </div>
        </div>
    </div>
</div>


@endsection

resources/views/proveedores/edit.blade.php
@extends('layouts.backend')

@section('content')
<div class="wrapper">
    <div class="row">
        <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Editar proveedor</h5>
            </div>
            <div class="ibox-content">
                <div class="row">
                    
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <strong>Ups!</strong> Hay algunos inconvenientes en el formulario.<br><br>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    
                    <div class="row wrapper">
                        <form action="{{ route('proveedores.update', $proveedor->ID) }}" method="POST">
                            @csrf
                            @method('PUT')
                            @include('proveedores.fragment.form')
                        </form>
                    </div>
                    
                    
                </div>
            </div>
        </div>
        </div>
    </div>
</div>


@endsection

resources/views/proveedores/index.blade.php
@extends('layouts.backend')

@section('css')
	<link href="{{ asset('/backend/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('/backend/font-awesome/css/font-awesome.css') }}" rel="stylesheet">

    <link href="{{ asset('/backend/css/plugins/dataTables/datatables.min.css') }}" rel="stylesheet">

    <link href="{{ asset('/backend/css/animate.css') }}" rel="stylesheet">
    <link href="{{ asset('/backend/css/style.css') }}" rel="stylesheet">
@stop
	
@section('content')
<div class="wrapper">
    <div class="row">
        <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Proveedores</h5>
            </div>
            <div class="ibox-content">
                <div class="row">
                    <div class="col-lg-12">
                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif
                    </div>
                    <div class="col-lg-12">
                        <a class="btn btn-sm btn-success" href="{{ route('proveedores.create') }}" ><i class="fa fa-plus"></i> Nuevo</a>
                        <a class="btn btn-sm btn-primary" href="{{ url ('exportarExcel') }}"><i class="fa fa-file-excel-o"></i> Excel</a>
                        <a class="btn btn-sm btn-danger" href="{{ url ('exportarPDF') }}"><i class="fa fa-file-pdf-o"></i> Pdf</a>
                        
                    </div>
                    <div class="col-lg-10">
                        <table class="table table-striped table-bordered table-hover dataTables-example">
                            <tr>
                                <th>Código</th>
                                <th>Apellido y Nombre</th>
                                <th>Razon Social</th>
                                <th>Cuil</th>
                                <th>Acción</th>
                            </tr>
                            @foreach ($proveedores as $proveedor)
                            <tr>
                                <td style="width: 10%;">{{ $proveedor->CODIGO }}</td>
                                <td style="width: 20%;">{{ $proveedor->NOMBRE }}</td>
                                <td style="width: 20%;">{{ $proveedor->RAZON_SOCIAL }}</td>
                                <td style="width: 20%;">{{ $proveedor->CUIL }}</td>
                                <td style="width: 10%;">
                                    <form action="{{ route('proveedores.destroy', $proveedor->ID ) }}" method="POST">
                                        <a title="Ver" class="btn btn-xs btn-info" href="{{ route('proveedores.show',$proveedor->ID) }}"><i class="fa fa-eye"></i></a>
                                        <a title="Editar" class="btn btn-xs btn-primary" href="{{ route('proveedores.edit',$proveedor->ID) }}"><i class="fa fa-edit"></i></a>
                                        @csrf
                                        @method('DELETE')
                                        <button title="Eliminar" type="submit" class="btn btn-xs btn-danger"><i class="fa fa-trash"></i></button>
                                    </form>
                                </td>
                                
                            </tr>
                            @endforeach
                        </table>
                        {!! $proveedores->links() !!}
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>
</div>




@endsection

@section('javascrip')
	<script src="{{ asset('/backend/js/jquery-3.1.1.min.js') }}"></script> 
    <script src="{{ asset('/backend/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('/backend/js/plugins/metisMenu/jquery.metisMenu.js') }}"></script>
    <script src="{{ asset('/backend/js/plugins/slimscroll/jquery.slimscroll.min.js') }}"></script>

    <script src="{{ asset('/backend/js/plugins/dataTables/datatables.min.js') }}"></script>

    <!-- Custom and plugin javascript -->
    <script src="{{ asset('/backend/js/inspinia.js') }}"></script>
    <script src="{{ asset('/backend/js/plugins/pace/pace.min.js') }}"></script>

    <!-- Page-Level Scripts -->
    <script>
        $(document).ready(function(){
            $('.dataTables-example').DataTable({
                pageLength: 25,
                responsive: true,
                dom: '<"html5buttons"B>lTfgitp',
                buttons: [
                    { extend: 'copy'},
                    {extend: 'csv'},
                    {extend: 'excel', title: 'ExampleFile'},
                    {extend: 'pdf', title: 'ExampleFile'},

                    {extend: 'print',
                     customize: function (win){
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');

                            $(win.document.body).find('table')
                                    .addClass('compact')
                                    .css('font-size', 'inherit');
                    }
                    }
                ]

            });

        });

    </script>
@stop

resources/views/proveedores/show.blade.php
@extends('layouts.backend')

@section('content')
<div class="wrapper">
    <div class="row">
        <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Proveedor</h5>
            </div>
            <div class="ibox-content">
                <div class="row">
                    
                    
                    <form action="#" method="POST">
                        @csrf
                         <div class="row wrapper">
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <strong>Código:</strong>
                                    <input value="{{ $proveedor->CODIGO }}" type="number" name="codigo" class="form-control" placeholder="Código" readonly="">
                                </div>
                            </div>
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <strong>Nombre:</strong>
                                    <input value="{{ $proveedor->NOMBRE }}" type="text" name="nombre" class="form-control" placeholder="Nombre" readonly="">
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                               <div class="form-group">
                                    <strong>Razón Social:</strong>
                                    <input value="{{ $proveedor->RAZON_SOCIAL }}" type="text" name="razon_social" class="form-control" placeholder="Razon_social" readonly="">
                                </div>
                            </div>
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <strong>CUIL:</strong>
                                    <input value="{{ $proveedor->CUIL }}" type="number" name="cuil" class="form-control" placeholder="CUIL" readonly="">
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                               <div class="form-group">
                                    <strong>Domicilio:</strong>
                                    <input value="{{ $proveedor->DOMICILIO }}" type="text" name="domicilio" class="form-control" placeholder="Domicilio" readonly="">
                                </div>
                            </div>
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <strong>Teléfono:</strong>
                                    <input value="{{ $proveedor->TELEFONO }}" type="number" name="telefono" class="form-control" placeholder="Telefono" readonly="">
                                </div>
                            </div>
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <strong>Email:</strong>
                                    <input value="{{ $proveedor->EMAIL }}" type="email" name="email" class="form-control" placeholder="Email" readonly="">
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Observaciones:</strong>
                                    <textarea name="observaciones" class="form-control" placeholder="Observaciones..." readonly="">{{ $proveedor->OBSERVACIONES }}</textarea>
                                </div>
                            </div>
                            
                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                    <a class="btn btn-primary" href="{{ route('proveedores.index') }}"> Regresar</a>
                            </div>
                        </div>


                    </form>
                    
                </div>
            </div>
        </div>
        </div>
    </div>
</div>








    
    
    

@endsection