routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/exportarExcel', 'HomeController@export');
Route::get('/exportarPDF', 'HomeController@exportarPDF');

Route::resource('/cuentas','PlanCuentasController');

Route::resource('/proveedores','ProovedoresController');
Route::resource('/ordenes-de-pago','OrdenPagoController');
Route::get('/exportar-orden-pago/{id}', 'OrdenPagoController@exportarOrdenPago');

Route::get('/ver-op',function(){
    return view('reportes.orden_pago');
   // $letras = NumeroALetras::convertir(12345);
    //echo $letras;
});

Route::get('/exportar-orden-pago/{id}','OrdenPagoController@exportarOrdenPago');

Route::get('/exportarExcel', 'ProovedoresController@export');
Route::get('/exportarPDF', 'ProovedoresController@exportarPDF');

Route::get('/eliminarcuenta/{id}', 'PlanCuentasController@eliminarCuenta');
Route::post('/actualizarcuenta/', 'PlanCuentasController@actualizarCuenta')->name('actualizarcuenta');

//Route::get('/orden-de-pago','OrdenPagoController@index');

//Creditos de ejercicios 

Route::resource('/creditos-del-ejercicio','CreditoEjercicioController');
Route::get('/creditos-del-ejercicio.presupuesto','CreditoEjercicioController@presupuesto')->name('creditos-del-ejercicio.presupuesto');
Route::get('/creditos-del-ejercicio.compensacion','CreditoEjercicioController@compensacion')->name('creditos-del-ejercicio.compensacion');

Route::get('/pagos/pagar-orden-pago/{id}' , 'PagosController@payOrder')->name('pagos.create');

Route::post('/pagos/guardar-pago' , 'PagosController@savePayment')->name('pagos.guardar');

Route::get('/pagos','PagosController@index')->name('pagos.index');
Route::post('/pagos/disponibilidad-cheque' , 'PagosController@verificarDisponibilidadCheque');

app/Models/Cuenta.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\MovCuenta;

class Cuenta extends Model
{
    protected $table = 'CUENTAS';
//    protected $guarded = ["ID"];
    
    protected $fillable = [
        'codigo', 'nombre','id_cuenta_superior','observaciones','PRESUPUESTO','PRESUPUESTO_EJECUTIVO','PRESUPUESTO_LEGISLATIVO','saldo','is_principal','creado_por','modificado_por'
    ];

    public function nombreCuentaSuperior()
    {
        
        return $this->belongsTo('App\Models\Cuenta','ID_CUENTA_SUPERIOR');
        
    }

    public function cuentasuperior(){
        return $this->belongsTo('App\Models\Cuenta','ID_CUENTA_SUPERIOR');
    }

    public function cuentamov()
    {
        return $this->hasOne('App\Models\MovCuenta','FK_CUENTA');
        //return $this->hasOne('App\Models\MovCuenta','FK_CUENTA_DEBITAR');
    }

     public function cuentamovdebitar()
    {
        return $this->hasOne('App\Models\MovCuenta','FK_CUENTA_DEBITAR');
    }

    public function perteneceAPresupuestoPago($cuenta){

        $cuentaObj = Cuenta::findOrFail($cuenta->ID);

        if($cuentaObj->ID_CUENTA_SUPERIOR != NULL){

            while($cuentaObj->ID_CUENTA_SUPERIOR != NULL){     
                $cuentaObj = Cuenta::findOrFail($cuentaObj->ID_CUENTA_SUPERIOR);
            }
            
            if($cuentaObj->ID == 149)
                return true;
            else
                return false;

        }else{

            if($cuentaObj->ID == 149)
                return true;
            else
                return false;

        }
        
    }

}

resources/views/cuentas/create.blade.php
@extends('layouts.backend')

@section('content')
<div class="wrapper">
    <div class="row">
        <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Cuentas</h5>
            </div>
            <div class="ibox-content">
                <div class="row">
                    
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <strong>Whoops!</strong> Hay algunos inconvenientes en el formulario.<br><br>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    
                    <form action="{{ route('cuentas.store') }}" method="POST">
                        @csrf

                         <div class="row wrapper">
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <strong>Código:</strong>
                                    <input type="text" name="codigo" value="{{ $next_codigo }}" class="form-control" placeholder="Código">
                                </div>
                            </div>
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <strong>Nombre:</strong>
                                    <input type="text" name="nombre" class="form-control" placeholder="Nombre">
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Cuenta Superior:</strong>
                                    <select type="text" name="id_cuenta_superior" class="form-control" placeholder="Cuenta Superior">
                                        <option value="null"tabindex="-1">Seleccione una opción...</option>
                                        @foreach($cuentas as $cuenta)
                                        <option value="{{ $cuenta->ID }}">{{ $cuenta->CODIGO }} - {{ $cuenta->NOMBRE }}</option>
                                        @endforeach
                                    
                                    </select>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Observaciones:</strong>
                                    <textarea name="observaciones" class="form-control" placeholder="Observaciones..."></textarea>
                                </div>
                            </div>
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <strong>PRESUPUESTO:</strong>
                                    <input type="number" name="presupuesto" class="form-control" placeholder="$ 0">
                                </div>
                            </div>
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <strong>PRESUPUESTO EJECUTIVO:</strong>
                                        <input type="number" name="presupuesto_ejecutivo" class="form-control" placeholder="$ 0">
                                    </div>
                                </div>
                                <div class="col-xs-6 col-sm-6 col-md-6">
                                        <div class="form-group">
                                            <strong>PRESUPUESTO LEGISLATIVO:</strong>
                                            <input type="number" name="presupuesto_legislativo" class="form-control" placeholder="$ 0">
                                        </div>
                                    </div>
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <strong>Cuenta Principal:</strong>
                                    <input type="checkbox" name="is_principal" class="form-control" >
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                    <button type="submit" class="btn btn-primary">Crear</button>
                                    <a class="btn btn-default" href="{{ route('cuentas.index') }}"> Regresar</a>
                            </div>
                        </div>


                    </form>
                    
                </div>
            </div>
        </div>
        </div>
    </div>
</div>


@endsection

@section('javascript')
    <script>
        $(document).ready(function(){
            $.ajax({
                url: '/buscarSgteNroCuenta',
                data: { "_token": "{{ csrf_token() }}",
                        id_cuenta_superior   : $('[name="id_cuenta_superior"]').val()
                },
                success: function(){
                    
                },
                error: function(){
                    
                }
            });
        });
    </script>
@stop

resources/views/cuentas/edit.blade.php
@extends('layouts.backend')

@section('content')
<div class="wrapper">
    <div class="row">
        <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Cuentas</h5>
            </div>
            <div class="ibox-content">
                <div class="row">
                    
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <strong>Whoops!</strong> Hay algunos inconvenientes en el formulario.<br><br>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    
                    <form action="{{ route('actualizarcuenta') }}" method="POST">
                        @csrf
                        <input name="idcuenta" value="{{$cuenta->ID}}" type="hidden">
                         <div class="row wrapper">
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <strong>Código:</strong>
                                    <input value="{{ $cuenta->CODIGO }}" type="text" name="codigo" class="form-control" placeholder="Código" disabled="">
                                </div>
                            </div>
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <strong>Nombre:</strong>
                                    <input value="{{ $cuenta->NOMBRE }}" type="text" name="nombre" class="form-control" placeholder="Nombre">
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Cuenta Superior:</strong>
                                    <select type="text" name="id_cuenta_superior" class="form-control" placeholder="Cuenta Superior">
                                        @foreach($cuentas as $c)
                                            @if($c->ID == $cuenta->ID_CUENTA_SUPERIOR)
                                                <option value="{{ $c->ID }}" selected="">{{ $c->CODIGO . " - " . $c->NOMBRE }}</option>
                                            @else
                                                <option value="{{ $c->ID }}" >{{ $c->CODIGO . " - " . $c->NOMBRE  }}</option>
                                            @endif
                                        @endforeach

                                    </select>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Observaciones:</strong>
                                    <textarea name="observaciones" class="form-control" placeholder="Observaciones...">{{ $cuenta->OBSERVACIONES }}</textarea>
                                </div>
                            </div>
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <strong>PRESUPUESTO:</strong>
                                        <input type="number" name="presupuesto" value="{{ $cuenta->PRESUPUESTO }}" class="form-control" placeholder="$ 0">
                                    </div>
                                </div>
                                <div class="col-xs-6 col-sm-6 col-md-6">
                                        <div class="form-group">
                                            <strong>PRESUPUESTO EJECUTIVO:</strong>
                                            <input type="number" value="{{ $cuenta->PRESUPUESTO_EJECUTIVO }}" name="presupuesto_ejecutivo" class="form-control" placeholder="$ 0">
                                        </div>
                                    </div>
                                    <div class="col-xs-6 col-sm-6 col-md-6">
                                            <div class="form-group">
                                                <strong>PRESUPUESTO LEGISLATIVO:</strong>
                                                <input type="number" value="{{ $cuenta->PRESUPUESTO_LEGISLATIVO }}" name="presupuesto_legislativo" class="form-control" placeholder="$ 0">
                                            </div>
                                    </div>
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <strong>Cuenta Principal:</strong>
                                    @if($cuenta->IS_PRINCIPAL == 1)
                                        <input type="checkbox" name="is_principal" class="form-control" checked="">
                                    @else
                                        <input type="checkbox" name="is_principal" class="form-control" >
                                    @endif
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                    <button type="submit" class="btn btn-primary">Guardar</button>
                                    <a class="btn btn-default" href="{{ route('cuentas.index') }}"> Regresar</a>
                            </div>
                        </div>
                    </form>
                    
                </div>
            </div>
        </div>
        </div>
    </div>
</div>








    
    
    

@endsection

resources/views/cuentas/index.blade.php
@extends('layouts.backend')

@section('css')
    <!-- Required Stylesheets -->
    {{-- <link href="/bower_components/bootstrap-treeview/src/css/bootstrap-treeview.css" rel="stylesheet"> --}}
    <link href="/backend/css/dataTables/datatables.min.css" rel="stylesheet">
    
@stop

@section('content')
<div class="wrapper">
    <div class="row">
        <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Cuentas</h5>
            </div>
            <div class="ibox-content">
                <div class="row">
                        <div class="col-lg-12">
                                @if ($message = Session::get('success'))
                                    <div class="alert alert-success">
                                        <p>{{ $message }}</p>
                                    </div>
                                @endif
                        </div>
                    {{-- <div class="col-lg-12">
                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif
                    </div>
                    <div class="col-lg-12">
                        <a class="btn btn-sm btn-primary" href="{{ route('cuentas.create') }}" > Nueva Cuenta</a>
                    </div> --}}
                    {{-- <div class="col-lg-12 m-t-md">
                        <table class="table table-bordered">
                            <tr>
                                <th>Código</th>
                                <th>Nombre</th>
                                <th>Observaciones</th>
                                <th>Saldo</th>
                                <th width="280px">Acción</th>
                            </tr>
                            @foreach ($cuentas as $cuenta)
                            <tr>
                                <td style="width: 20%;">{{ $cuenta->CODIGO }}</td>
                                <td style="width: 20%;">{{ $cuenta->NOMBRE }}</td>
                                <td style="width: 30%;">{{ $cuenta->OBSERVACIONES }}</td>
                                <td style="width: 10%;">{{ $cuenta->SALDO }}</td>
                                <td style="width: 20%;">
                                    <form action="{{ route('cuentas.destroy', $cuenta->ID ) }}" method="POST">
                                        <a title="Ver" class="btn btn-xs btn-info" href="{{ route('cuentas.show',$cuenta->ID) }}"><i class="fa fa-eye"></i></a>
                                        <a title="Editar" class="btn btn-xs btn-primary" href="{{ route('cuentas.edit',$cuenta->ID) }}"><i class="fa fa-edit"></i></a>
                                        @csrf
                                        @method('DELETE')
                                        <button title="Eliminar" type="submit" class="btn btn-xs btn-danger"><i class="fa fa-trash"></i></button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </table>
                        {!! $cuentas->links() !!}
                    </div> --}}
                    <div class="col-lg-12">
                          <div class="row">
                            {{-- <hr> --}}
                            <div class="col-sm-12">
                              
                              <div class="form-group row">
                                <div class="col-sm-12">
                                  <a class="btn btn-sm btn-primary" href="{{ route('cuentas.create') }}" > Nueva Cuenta</a>
                                </div>
                              </div>
                            </div>
                            <div class="col-sm-12">
                              

                                <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover dataTables-example" >
                            <thead>
                            <tr>
                                
                                <th>Código</th>
                                <th>Nombre</th>
                                <th>Cuenta Superior</th>
                                <th>Presupuesto</th>
                                <th>Presupuesto Ejecutivo</th>
                                <th>Presupuesto Legislativo</th>
                                <th>Saldo</th>
                                <th>Acción</th>
                            </tr>
                            </thead>
                            <tbody>
                            
                            <?php
                              foreach($cuentas as $cuenta){
                                echo "<tr>";
                               
                                echo "<td>" . $cuenta->CODIGO ."</td>";
                                echo "<td>". $cuenta->NOMBRE ."</td>";
                                echo "<td>". $cuenta->nombreCuentaSuperior["CODIGO"] . ' - ' .$cuenta->nombreCuentaSuperior["NOMBRE"] ."</td>";
                                echo "<td>". number_format($cuenta->PRESUPUESTO,2,",",".") ."</td>";
                                echo "<td>". number_format($cuenta->PRESUPUESTO_EJECUTIVO,2,",",".") ."</td>";
                                echo "<td>". number_format($cuenta->PRESUPUESTO_LEGISLATIVO,2,",",".") ."</td>";
                                echo "<td>". number_format($cuenta->SALDO,2,",",".") ."</td>";
                            ?>
                                <td>
                                    <a href="/eliminarcuenta/<?php echo $cuenta->ID; ?>"><button title='Eliminar' class='btn btn-xs btn-danger eliminar'><i class='fa fa-trash'></i></button></a>
                                    <a href="/cuentas/<?php echo $cuenta->ID; ?>/edit"><button title='Editar' class='btn btn-xs btn-default'><i class='fa fa-edit'></i></button></a>
                                </td>
                            <?php
                                echo "</tr>";
                              }
                            ?>
                            
                            </tbody>
                            <tfoot>
                            <tr>
                                
                                <th>Código</th>
                                <th>Nombre</th>
                                <th>Cuenta Superior</th>
                                <th>Presupuesto</th>
                                <th>Presupuesto Ejecutivo</th>
                                <th>Presupuesto Legislativo</th>
                                <th>Saldo</th>
                                <th>Acción</th>
                            </tr>
                            </tfoot>
                            </table>
                                </div>
        
                            
                            </div>
                          </div>
                    </div>
                    
                </div>
            </div>
        </div>
        </div>
    </div>
</div>

@endsection

@section('javascript')
    
    {{-- <script src="/bower_components/bootstrap-treeview/src/js/bootstrap-treeview.js"></script> --}}
    <script src="/backend/js/plugins/dataTables/datatables.min.js"></script>
    <script>
      $(document).ready(function(){
          $('.dataTables-example').DataTable({
              pageLength: 25,
              responsive: true,
              dom: '<"html5buttons"B>lTfgitp',
              buttons: [
                  { extend: 'copy'},
                  {extend: 'csv'},
                  {extend: 'excel', title: 'PlanDeCuentas'},
                  {extend: 'pdf', title: 'PlanDeCuentas'},

                  {extend: 'print',
                   customize: function (win){
                          $(win.document.body).addClass('white-bg');
                          $(win.document.body).css('font-size', '10px');

                          $(win.document.body).find('table')
                                  .addClass('compact')
                                  .css('font-size', 'inherit');
                  }
                  }
              ]

          });

          
          
          
          

      });

        
  </script>

@stop

resources/views/cuentas/show.blade.php
@extends('layouts.backend')

@section('content')
<div class="wrapper">
    <div class="row">
        <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Cuentas</h5>
            </div>
            <div class="ibox-content">
                <div class="row">
                    
                    
                    <form action="#" method="POST">
                        @csrf

                         <div class="row wrapper">
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <strong>Código:</strong>
                                    <input value="{{ $cuenta->CODIGO }}" type="text" name="codigo" class="form-control" placeholder="Código" readonly="">
                                </div>
                            </div>
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <strong>Nombre:</strong>
                                    <input value="{{ $cuenta->NOMBRE }}" type="text" name="nombre" class="form-control" placeholder="Nombre" readonly="">
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Cuenta Superior:</strong>
                                    <input value="{{ $cuenta_superior_desc }}" type="text" name="id_cuenta_superior" class="form-control" placeholder="Nombre" readonly="">
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Observaciones:</strong>
                                    <textarea name="observaciones" class="form-control" placeholder="Observaciones..." readonly="">{{ $cuenta->OBSERVACIONES }}</textarea>
                                </div>
                            </div>
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <strong>Saldo:</strong>
                                    <input type="number" value="{{ $cuenta->SALDO }}" name="saldo" class="form-control" placeholder="$ 0" readonly="">
                                </div>
                            </div>
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <strong>Cuenta Principal:</strong>
                                    @if($cuenta->IS_PRINCIPAL)
                                    <input type="checkbox" name="is_principal" class="form-control" checked="" readonly="">
                                    @else
                                    <input type="checkbox" name="is_principal" class="form-control"  readonly="">
                                    @endif
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                    <a class="btn btn-default" href="{{ route('cuentas.index') }}"> Regresar</a>
                            </div>
                        </div>


                    </form>
                    
                </div>
            </div>
        </div>
        </div>
    </div>
</div>








    
    
    

@endsection